DROP DATABASE IF EXISTS mck_voters_db;
CREATE DATABASE mck_voters_db;
USE mck_voters_db;
CREATE TABLE voters
(
precinct_desc CHAR(7),
party_cd CHAR(3),
race_code CHAR(1),
ethnic_code CHAR(2),
sex_code CHAR(1),
age INT,
pct_portion DECIMAL(9,6),
first_name VARCHAR(25),
middle_name VARCHAR(25),
last_name VARCHAR(25),
name_suffix_lbl VARCHAR(10),
full_name_mail VARCHAR(75),
mail_addr1 VARCHAR(80),
mail_addr2 VARCHAR(80),
mail_addr3 VARCHAR(80),
mail_addr4 VARCHAR(80),
mail_city_state_zip VARCHAR(80),
house_num VARCHAR(20),
half_code VARCHAR(40),
street_dir VARCHAR(40),
street_name VARCHAR(40),
street_type_cd CHAR(2),
street_sufx_cd VARCHAR(20),
unit_designator VARCHAR(20),
unit_num VARCHAR(20),
res_city_desc VARCHAR(20),
state_cd CHAR(2),
zip_code INT,
registr_dt DATETIME,
voter_reg_num BIGINT,
status_cd CHAR(2),
municipality_desc VARCHAR(40),
ward_desc VARCHAR(40),
cong_dist_desc VARCHAR(40),
super_court_desc VARCHAR(40),
judic_dist_desc VARCHAR(40),
nc_senate_desc VARCHAR(40),
nc_house_desc VARCHAR(40),
county_commiss_desc VARCHAR(40),
school_dist_desc VARCHAR(40),
dist_1_desc VARCHAR(40),
E1 INT,
E1_Date DATE,
E1_VotingMethod CHAR(1),
E1_PartyCd CHAR(3),
E2 INT,
E2_Date DATE,
E2_VotingMethod CHAR(1),
E2_PartyCd CHAR(3),
E3 INT,
E3_Date DATE,
E3_VotingMethod CHAR(1),
E3_PartyCd CHAR(3),
E4 INT,
E4_Date DATE,
E4_VotingMethod CHAR(1),
E4_PartyCd CHAR(3),
E5 INT,
E5_Date DATE,
E5_VotingMethod CHAR(1),
E5_PartyCd CHAR(3),
E6 INT,
E6_Date DATE,
E6_VotingMethod CHAR(1),
E6_PartyCd CHAR(3),
E7 INT,
E7_Date DATE,
E7_VotingMethod CHAR(1),
E7_PartyCd CHAR(3),
E8 INT,
E8_Date DATE,
E8_VotingMethod CHAR(1),
E8_PartyCd CHAR(3),
E9 INT,
E9_Date DATE,
E9_VotingMethod CHAR(1),
E9_PartyCd CHAR(3),
E10 INT,
E10_Date DATE,
E10_VotingMethod CHAR(1),
E10_PartyCd CHAR(3),
E11 INT,
E11_Date DATE,
E11_VotingMethod CHAR(1),
E11_PartyCd CHAR(3),
E12 INT,
E12_Date DATE,
E12_VotingMethod CHAR(1),
E12_PartyCd CHAR(3),
E13 INT,
E13_Date DATE,
E13_VotingMethod CHAR(1),
E13_PartyCd CHAR(3),
E14 INT,
E14_Date DATE,
E14_VotingMethod CHAR(1),
E14_PartyCd CHAR(3),
E15 INT,
E15_Date DATE,
E15_VotingMethod CHAR(1),
E15_PartyCd CHAR(3),
E16 INT,
E16_Date DATE,
E16_VotingMethod CHAR(1),
E16_PartyCd CHAR(3),
E17 INT,
E17_Date DATE,
E17_VotingMethod CHAR(1),
E17_PartyCd CHAR(3),
E18 INT,
E18_Date DATE,
E18_VotingMethod CHAR(1),
E18_PartyCd CHAR(3),
E19 INT,
E19_Date DATE,
E19_VotingMethod CHAR(1),
E19_PartyCd CHAR(3),
E20 INT,
E20_Date DATE,
E20_VotingMethod CHAR(1),
E20_PartyCd CHAR(3)
);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 5.7/Uploads/voterdatafile.txt'
INTO TABLE voters 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(precinct_desc,party_cd,race_code,ethnic_code,sex_code,age,pct_portion,first_name,middle_name,last_name,name_suffix_lbl,full_name_mail,mail_addr1,mail_addr2,mail_addr3,mail_addr4,mail_city_state_zip,house_num,half_code,street_dir,street_name,street_type_cd,street_sufx_cd,unit_designator,unit_num,res_city_desc,state_cd,zip_code,@var1,voter_reg_num,status_cd,municipality_desc,ward_desc,cong_dist_desc,super_court_desc,judic_dist_desc,nc_senate_desc,nc_house_desc,county_commiss_desc,school_dist_desc,dist_1_desc,E1,@var2,E1_VotingMethod,E1_PartyCd,E2,@var3,E2_VotingMethod,E2_PartyCd,E3,@var4,E3_VotingMethod,E3_PartyCd,E4,@var5,E4_VotingMethod,E4_PartyCd,E5,@var6,E5_VotingMethod,E5_PartyCd,E6,@var7,E6_VotingMethod,E6_PartyCd,E7,@var8,E7_VotingMethod,E7_PartyCd,E8,@var9,E8_VotingMethod,E8_PartyCd,E9,@var10,E9_VotingMethod,E9_PartyCd,E10,@var11,E10_VotingMethod,E10_PartyCd,E11,@var12,E11_VotingMethod,E11_PartyCd,E12,@var13,E12_VotingMethod,E12_PartyCd,E13,@var14,E13_VotingMethod,E13_PartyCd,E14,@var15,E14_VotingMethod,E14_PartyCd,E15,@var16,E15_VotingMethod,E15_PartyCd,E16,@var17,E16_VotingMethod,E16_PartyCd,E17,@var18,E17_VotingMethod,E17_PartyCd,E18,@var19,E18_VotingMethod,E18_PartyCd,E19,@var20,E19_VotingMethod,E19_PartyCd,E20,@var21,E20_VotingMethod,E20_PartyCd)
SET registr_dt = STR_TO_DATE(@var1,'%c/%e/%Y %T'),
set E1_Date = STR_TO_DATE(@var2,'%c/%e/%Y');
/*SET E2_Date = STR_TO_DATE(@var3,'%c/%e/%Y'),
SET E3_Date = STR_TO_DATE(@var4,'%c/%e/%Y'),
SET E4_Date = STR_TO_DATE(@var5,'%c/%e/%Y'),
SET E5_Date = STR_TO_DATE(@var6,'%c/%e/%Y'),
SET E6_Date = STR_TO_DATE(@var7,'%c/%e/%Y'),
SET E7_Date = STR_TO_DATE(@var8,'%c/%e/%Y'),
SET E8_Date = STR_TO_DATE(@var9,'%c/%e/%Y'),
SET E9_Date = STR_TO_DATE(@var10,'%c/%e/%Y'),
SET E10_Date = STR_TO_DATE(@var11,'%c/%e/%Y'),
SET E11_Date = STR_TO_DATE(@var12,'%c/%e/%Y'),
SET E12_Date = STR_TO_DATE(@var13,'%c/%e/%Y'),
SET E13_Date = STR_TO_DATE(@var14,'%c/%e/%Y'),
SET E14_Date = STR_TO_DATE(@var15,'%c/%e/%Y'),
SET E15_Date = STR_TO_DATE(@var16,'%c/%e/%Y'),
SET E16_Date = STR_TO_DATE(@var17,'%c/%e/%Y'),
SET E17_Date = STR_TO_DATE(@var18,'%c/%e/%Y'),
SET E18_Date = STR_TO_DATE(@var19,'%c/%e/%Y'),
SET E19_Date = STR_TO_DATE(@var20,'%c/%e/%Y'),
SET E20_Date = STR_TO_DATE(@var21,'%c/%e/%Y');
